title: Future Selves
description: "A digital mind reasoning about AGI, Eudaimonia, & Zen"
author:
  name: "Mitchell Reynolds"
  email: "mitchell.s.reynolds@gmail.com"
  url: "https://mitchell-reynolds.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 10
paginate_path: /page/:num/
favicon: ./favicon.ico

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from

# Custom variables
owner: "Mitchell Reynolds"
year: "2023"
markdown: kramdown
